version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: btf-nginx
    working_dir: /app
    volumes:
        - .:/app
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
     - "80:80"

  fpm:
    build: docker/fpm
    container_name: btf-fpm
    working_dir: /app
    volumes:
        - .:/app
